# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0d928aeabfff17aaf7378755ef81c77c1da5d42c7c3d33fadee469e429770eea39491744a1085a028095d973d4b9c2cb5cb62a3b03971bf33dbffb017a90d2f

test:
  secret_key_base: 21c4e97a4d828659c83cbde6c8ef91c301780c32217feba959bd5afab29dba9cf59f7bf45f71e4473963116e3b2fd399aab56b630b613a84963d5b17a943e8c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
